server:
  port: 8080
  host: "0.0.0.0"

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "/var/log/webhook-proxy.log"

endpoints:
  - path: "/webhook/github"
    destinations:
      - url: "https://destination1.example.com/webhook"
        method: "POST"
        headers:
          Content-Type: "application/json"
          X-Custom-Header: "value"
        timeout: 5s
        retries: 3
        retry_delay: 1s
      - url: "https://destination2.example.com/webhook"
        method: "POST"
        timeout: 3s
        retries: 2
  
  - path: "/webhook/gitlab"
    destinations:
      - url: "https://destination3.example.com/webhook"
        method: "POST" 