apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webhook-proxy.fullname" . }}-config
  labels:
    {{- include "webhook-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      host: {{ .Values.config.server.host | quote }}
      port: {{ .Values.config.server.port }}
    
    logging:
      level: {{ .Values.config.logging.level | quote }}
      format: {{ .Values.config.logging.format | quote }}
      output: {{ .Values.config.logging.output | quote }}
      {{- if .Values.config.logging.file_path }}
      file_path: {{ .Values.config.logging.file_path | quote }}
      {{- end }}
    
    endpoints:
      {{- if .Values.config.endpoints }}
      {{- toYaml .Values.config.endpoints | nindent 6 }}
      {{- end }} 